### PR TITLE
Improved Dark Mode

### PR DESCRIPTION
**Pull request by darpan5552**
Now, also changing font color to white in dark mode
Changed color of run button to match both color modes

I have only included armeabi-v7 debug binaries. Please, create others yourself to avoid signing issues.
Code tested, running properly on Redmi note 8.

### CODE REVIEW

**Comment by darpan5552** [comment]
Surprisingly, app created by me doesn't contain any of text input problems that earlier exist. 

I have a slow internet connection for downloading such huge packages of buildozer every time for other projects. So, i copied bulky dependencies to a seperate folder and then copy back to `.buildozer` at time of building. 
This means the problem is in the latest dependencies, a month old dependencies are fine for me.

**Comment by kengoon** [comment]
> Surprisingly, app created by me doesn't contain any of text input problems that earlier exist.
> 
> I have a slow internet connection for downloading such huge packages of buildozer every time for other projects. So, i copied bulky dependencies to a seperate folder and then copy back to `.buildozer` at time of building.
> This means the problem is in the latest dependencies, a month old dependencies are fine for me.

yes exactly, did you use requirement = kivy==2.0.0 ?

**Comment by darpan5552** [comment]
Yes, i used kivy==v2.0.0

**Comment by kengoon** [comment]
ok I was using the master branch, that's why. nice job though

**Pull request merged**
